update paths

diff --git a/run_autograder b/run_autograder
--- a/run_autograder
+++ b/run_autograder
@@ -10,7 +10,13 @@ source /autograder/source/exercise_name.sh
 
 # Check submission count
 conda activate grader
-python limit_num_submissions.py
+python /autograder/source/limit_num_submissions.py
+
+# Exit if not return code 0 from above
+if [ $? != 0 ];
+then
+    exit
+fi
 
 # Actually Grade
 cp /autograder/submission/${exercise_name}.ipynb /autograder/source/${exercise_name}.ipynb
